/**
 * Clases de Destreza: Ranger, Rogue, Assassin
 */

import {
    CharacterClass,
    ClassRole,
    ResourceType,
    PrimaryStat,
    WeaponType,
    ArmorType,
    SkillType,
    TargetType,
    EffectType,
    DamageType,
} from './types';

// ============================================
// RANGER (Cazador)
// ============================================

export const RANGER: CharacterClass = {
    id: 'ranger',
    name: 'Ranger',
    displayName: 'Cazador',
    description: 'Maestro del arco y la naturaleza. Ataca desde la distancia con precisión mortal.',
    roles: [ClassRole.DPS_RANGED],
    primaryStat: PrimaryStat.DEXTERITY,
    resourceType: ResourceType.FOCUS,
    resourceName: 'Concentración',
    baseStats: {
        health: 90,
        resource: 100,
        strength: 10,
        dexterity: 28,
        vitality: 12,
        intelligence: 8,
        faith: 5,
        wisdom: 10,
    },
    skills: [
        {
            id: 'steady_shot',
            name: 'Steady Shot',
            displayName: 'Disparo Certero',
            description: 'Disparo preciso que genera Concentración.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 28, scaling: 1.2, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'aimed_shot',
            name: 'Aimed Shot',
            displayName: 'Disparo Apuntado',
            description: 'Disparo cargado con alto daño y probabilidad de crítico.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 35,
            cooldown: 3,
            levelRequired: 8,
            effects: [
                { type: EffectType.DAMAGE, value: 60, scaling: 1.5, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'multi_shot',
            name: 'Multi-Shot',
            displayName: 'Disparo Múltiple',
            description: 'Dispara múltiples flechas a todos los enemigos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 40,
            cooldown: 4,
            levelRequired: 12,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 0.9, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'hunters_mark',
            name: 'Hunters Mark',
            displayName: 'Marca del Cazador',
            description: 'Marca al enemigo, aumentando el daño que recibe en un 25%.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 20,
            cooldown: 5,
            levelRequired: 6,
            effects: [
                { type: EffectType.DEBUFF, value: 25, scaling: 0, duration: 4 },
            ],
        },
        {
            id: 'explosive_trap',
            name: 'Explosive Trap',
            displayName: 'Trampa Explosiva',
            description: 'Coloca una trampa que explota causando daño de fuego.',
            type: SkillType.ACTIVE,
            targetType: TargetType.AOE_ENEMIES,
            resourceCost: 30,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 45, scaling: 0.7, damageType: DamageType.FIRE },
            ],
        },
        {
            id: 'call_companion',
            name: 'Call Companion',
            displayName: 'Llamar Compañero',
            description: 'Invoca un compañero animal que ayuda en batalla.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 50,
            cooldown: 8,
            levelRequired: 15,
            effects: [
                { type: EffectType.SUMMON, value: 1, scaling: 0, duration: 5 },
            ],
        },
    ],
    passives: [
        {
            id: 'eagle_eye',
            name: 'Eagle Eye',
            displayName: 'Ojo de Águila',
            description: 'Aumenta la probabilidad de crítico en un 10%.',
            levelRequired: 5,
            effects: [{ stat: 'critChance', value: 10, isPercentage: false }],
        },
        {
            id: 'quick_draw',
            name: 'Quick Draw',
            displayName: 'Mano Rápida',
            description: 'Aumenta la velocidad de ataque en un 15%.',
            levelRequired: 12,
            effects: [{ stat: 'attackSpeed', value: 15, isPercentage: true }],
        },
        {
            id: 'wild_instincts',
            name: 'Wild Instincts',
            displayName: 'Instintos Salvajes',
            description: 'Probabilidad de esquivar ataques aumentada en un 8%.',
            levelRequired: 18,
            effects: [{ stat: 'dodgeChance', value: 8, isPercentage: false }],
        },
    ],
    allowedWeapons: [WeaponType.BOW, WeaponType.CROSSBOW, WeaponType.DAGGER],
    allowedArmor: [ArmorType.LEATHER, ArmorType.MAIL],
};

// ============================================
// ROGUE (Pícaro)
// ============================================

export const ROGUE: CharacterClass = {
    id: 'rogue',
    name: 'Rogue',
    displayName: 'Pícaro',
    description: 'Luchador ágil que usa sigilo y venenos para debilitar y eliminar enemigos.',
    roles: [ClassRole.DPS_MELEE, ClassRole.SUPPORT],
    primaryStat: PrimaryStat.DEXTERITY,
    resourceType: ResourceType.ENERGY,
    resourceName: 'Energía',
    baseStats: {
        health: 85,
        resource: 100,
        strength: 8,
        dexterity: 30,
        vitality: 10,
        intelligence: 10,
        faith: 3,
        wisdom: 8,
    },
    skills: [
        {
            id: 'backstab',
            name: 'Backstab',
            displayName: 'Puñalada',
            description: 'Ataque rápido con daga. Genera energía.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 22, scaling: 1.1, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'eviscerate',
            name: 'Eviscerate',
            displayName: 'Eviscerar',
            description: 'Golpe final que consume Energía para causar gran daño.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 50,
            cooldown: 2,
            levelRequired: 5,
            effects: [
                { type: EffectType.DAMAGE, value: 70, scaling: 1.6, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'stealth',
            name: 'Stealth',
            displayName: 'Sigilo',
            description: 'Te vuelves invisible. El próximo ataque causa daño crítico garantizado.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 25,
            cooldown: 5,
            levelRequired: 8,
            effects: [
                { type: EffectType.BUFF, value: 100, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'poisoned_blade',
            name: 'Poisoned Blade',
            displayName: 'Hoja Envenenada',
            description: 'Ataque que aplica veneno, causando daño durante 4 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 30,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 20, scaling: 0.8, damageType: DamageType.POISON },
                { type: EffectType.DOT, value: 15, scaling: 0.3, duration: 4, damageType: DamageType.POISON },
            ],
        },
        {
            id: 'cheap_shot',
            name: 'Cheap Shot',
            displayName: 'Golpe Bajo',
            description: 'Aturde al enemigo por 1 turno.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 35,
            cooldown: 4,
            levelRequired: 12,
            effects: [
                { type: EffectType.DAMAGE, value: 15, scaling: 0.5, damageType: DamageType.PHYSICAL },
                { type: EffectType.STUN, value: 0, scaling: 0, duration: 1 },
            ],
        },
        {
            id: 'fan_of_knives',
            name: 'Fan of Knives',
            displayName: 'Abanico de Cuchillos',
            description: 'Lanza cuchillos a todos los enemigos cercanos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 40,
            cooldown: 3,
            levelRequired: 15,
            effects: [
                { type: EffectType.DAMAGE, value: 30, scaling: 0.8, damageType: DamageType.PHYSICAL },
            ],
        },
    ],
    passives: [
        {
            id: 'deadly_precision',
            name: 'Deadly Precision',
            displayName: 'Precisión Mortal',
            description: 'Daño crítico aumentado en un 30%.',
            levelRequired: 5,
            effects: [{ stat: 'critDamage', value: 30, isPercentage: false }],
        },
        {
            id: 'evasion',
            name: 'Evasion',
            displayName: 'Evasión',
            description: '15% de probabilidad de esquivar ataques.',
            levelRequired: 10,
            effects: [{ stat: 'dodgeChance', value: 15, isPercentage: false }],
        },
        {
            id: 'master_poisoner',
            name: 'Master Poisoner',
            displayName: 'Maestro Envenenador',
            description: 'Los venenos causan un 25% más de daño.',
            levelRequired: 18,
            effects: [{ stat: 'poisonDamage', value: 25, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.DAGGER, WeaponType.SWORD],
    allowedArmor: [ArmorType.LEATHER],
};

// ============================================
// ASSASSIN (Asesino)
// ============================================

export const ASSASSIN: CharacterClass = {
    id: 'assassin',
    name: 'Assassin',
    displayName: 'Asesino',
    description: 'Ejecutor silencioso que acumula combo points para ataques devastadores.',
    roles: [ClassRole.DPS_MELEE],
    primaryStat: PrimaryStat.DEXTERITY,
    resourceType: ResourceType.COMBO_POINTS,
    resourceName: 'Puntos de Combo',
    baseStats: {
        health: 80,
        resource: 5, // Max combo points
        strength: 10,
        dexterity: 32,
        vitality: 8,
        intelligence: 8,
        faith: 3,
        wisdom: 5,
    },
    skills: [
        {
            id: 'quick_stab',
            name: 'Quick Stab',
            displayName: 'Puñalada Rápida',
            description: 'Ataque rápido que genera 1 punto de combo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -1, // Genera combo point
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 20, scaling: 1.0, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'ambush',
            name: 'Ambush',
            displayName: 'Emboscada',
            description: 'Ataque desde las sombras. Crítico garantizado si estás en sigilo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -2,
            cooldown: 2,
            levelRequired: 5,
            effects: [
                { type: EffectType.DAMAGE, value: 45, scaling: 1.3, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'death_strike',
            name: 'Death Strike',
            displayName: 'Golpe Mortal',
            description: 'Consume todos los puntos de combo para un ataque devastador.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 5, // Consume todos
            cooldown: 1,
            levelRequired: 8,
            effects: [
                { type: EffectType.DAMAGE, value: 100, scaling: 2.0, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'shadowstep',
            name: 'Shadowstep',
            displayName: 'Paso Sombrío',
            description: 'Te teletransportas detrás del enemigo, generando combo points.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -2,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 1.1, damageType: DamageType.SHADOW },
            ],
        },
        {
            id: 'vanish',
            name: 'Vanish',
            displayName: 'Desvanecerse',
            description: 'Desapareces completamente, evitando el siguiente ataque.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 0,
            cooldown: 6,
            levelRequired: 12,
            effects: [
                { type: EffectType.BUFF, value: 100, scaling: 0, duration: 1 },
            ],
        },
        {
            id: 'blade_dance',
            name: 'Blade Dance',
            displayName: 'Danza de Espadas',
            description: 'Serie de cortes rápidos a todos los enemigos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 3,
            cooldown: 4,
            levelRequired: 18,
            effects: [
                { type: EffectType.DAMAGE, value: 50, scaling: 1.2, damageType: DamageType.PHYSICAL },
            ],
        },
    ],
    passives: [
        {
            id: 'assassinate',
            name: 'Assassinate',
            displayName: 'Asesinar',
            description: '50% más de daño a enemigos con menos del 25% de vida.',
            levelRequired: 5,
            effects: [{ stat: 'executeDamage', value: 50, isPercentage: true }],
        },
        {
            id: 'shadow_mastery',
            name: 'Shadow Mastery',
            displayName: 'Maestría de Sombras',
            description: 'El daño de sombra aumenta en un 20%.',
            levelRequired: 12,
            effects: [{ stat: 'shadowDamage', value: 20, isPercentage: true }],
        },
        {
            id: 'lethal_momentum',
            name: 'Lethal Momentum',
            displayName: 'Impulso Letal',
            description: 'Los ataques críticos generan un combo point adicional.',
            levelRequired: 18,
            effects: [{ stat: 'comboOnCrit', value: 1, isPercentage: false }],
        },
    ],
    allowedWeapons: [WeaponType.DAGGER],
    allowedArmor: [ArmorType.LEATHER],
};
