/**
 * Clases Híbridas: Cleric, Druid, Monk
 */

import {
    CharacterClass,
    ClassRole,
    ResourceType,
    PrimaryStat,
    WeaponType,
    ArmorType,
    SkillType,
    TargetType,
    EffectType,
    DamageType,
} from './types';

// ============================================
// CLERIC (Clérigo)
// ============================================

export const CLERIC: CharacterClass = {
    id: 'cleric',
    name: 'Cleric',
    displayName: 'Clérigo',
    description: 'Sanador sagrado dedicado a proteger y curar a sus aliados.',
    roles: [ClassRole.HEALER, ClassRole.SUPPORT],
    primaryStat: PrimaryStat.FAITH,
    secondaryStat: PrimaryStat.WISDOM,
    resourceType: ResourceType.HOLY_MANA,
    resourceName: 'Maná Sagrado',
    baseStats: {
        health: 80,
        resource: 150,
        strength: 8,
        dexterity: 6,
        vitality: 15,
        intelligence: 15,
        faith: 30,
        wisdom: 20,
    },
    skills: [
        {
            id: 'heal',
            name: 'Heal',
            displayName: 'Curar',
            description: 'Restaura vida a un aliado.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 20,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.HEAL, value: 50, scaling: 0.8 },
            ],
        },
        {
            id: 'greater_heal',
            name: 'Greater Heal',
            displayName: 'Curación Mayor',
            description: 'Curación poderosa de un solo objetivo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 40,
            cooldown: 2,
            levelRequired: 8,
            effects: [
                { type: EffectType.HEAL, value: 100, scaling: 1.2 },
            ],
        },
        {
            id: 'prayer_of_healing',
            name: 'Prayer of Healing',
            displayName: 'Oración de Curación',
            description: 'Cura a todos los aliados.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ALLIES,
            resourceCost: 60,
            cooldown: 4,
            levelRequired: 15,
            effects: [
                { type: EffectType.HEAL, value: 40, scaling: 0.6 },
            ],
        },
        {
            id: 'shield_of_faith',
            name: 'Shield of Faith',
            displayName: 'Escudo de Fe',
            description: 'Otorga un escudo que absorbe daño.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 30,
            cooldown: 3,
            levelRequired: 6,
            effects: [
                { type: EffectType.SHIELD, value: 60, scaling: 0.5, duration: 3 },
            ],
        },
        {
            id: 'resurrection',
            name: 'Resurrection',
            displayName: 'Resurrección',
            description: 'Revive a un aliado caído con el 50% de vida.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 100,
            cooldown: 10,
            levelRequired: 20,
            effects: [
                { type: EffectType.HEAL, value: 50, scaling: 0 }, // % of max health
            ],
        },
        {
            id: 'holy_smite',
            name: 'Holy Smite',
            displayName: 'Castigo Sagrado',
            description: 'Daño sagrado que es más efectivo contra no-muertos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 25,
            cooldown: 1,
            levelRequired: 3,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 0.7, damageType: DamageType.HOLY },
            ],
        },
        {
            id: 'regeneration',
            name: 'Regeneration',
            displayName: 'Regeneración',
            description: 'Cura al aliado gradualmente durante 5 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 25,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.HOT, value: 20, scaling: 0.3, duration: 5 },
            ],
        },
    ],
    passives: [
        {
            id: 'divine_grace',
            name: 'Divine Grace',
            displayName: 'Gracia Divina',
            description: 'Las curaciones son un 20% más efectivas.',
            levelRequired: 5,
            effects: [{ stat: 'healingPower', value: 20, isPercentage: true }],
        },
        {
            id: 'inner_peace',
            name: 'Inner Peace',
            displayName: 'Paz Interior',
            description: 'Regenera un 3% de maná cada turno.',
            levelRequired: 10,
            effects: [{ stat: 'manaRegen', value: 3, isPercentage: true }],
        },
        {
            id: 'blessed_resilience',
            name: 'Blessed Resilience',
            displayName: 'Resistencia Bendita',
            description: 'Vida máxima aumentada en un 15%.',
            levelRequired: 18,
            effects: [{ stat: 'maxHealth', value: 15, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.MACE, WeaponType.STAFF, WeaponType.SHIELD],
    allowedArmor: [ArmorType.CLOTH, ArmorType.MAIL],
};

// ============================================
// DRUID (Druida)
// ============================================

export const DRUID: CharacterClass = {
    id: 'druid',
    name: 'Druid',
    displayName: 'Druida',
    description: 'Guardián de la naturaleza que puede cambiar de forma y usar magia natural.',
    roles: [ClassRole.HYBRID, ClassRole.HEALER, ClassRole.DPS_MAGIC, ClassRole.TANK],
    primaryStat: PrimaryStat.WISDOM,
    secondaryStat: PrimaryStat.VITALITY,
    resourceType: ResourceType.NATURE,
    resourceName: 'Naturaleza',
    baseStats: {
        health: 95,
        resource: 100,
        strength: 12,
        dexterity: 12,
        vitality: 15,
        intelligence: 18,
        faith: 10,
        wisdom: 25,
    },
    skills: [
        {
            id: 'wrath',
            name: 'Wrath',
            displayName: 'Ira Natural',
            description: 'Ataque de energía natural.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 30, scaling: 1.0, damageType: DamageType.NATURE },
            ],
        },
        {
            id: 'bear_form',
            name: 'Bear Form',
            displayName: 'Forma de Oso',
            description: 'Transforma en oso, aumentando vida y defensa.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 20,
            cooldown: 5,
            levelRequired: 5,
            effects: [
                { type: EffectType.BUFF, value: 50, scaling: 0, duration: 4 }, // +50% vida
            ],
        },
        {
            id: 'wolf_form',
            name: 'Wolf Form',
            displayName: 'Forma de Lobo',
            description: 'Transforma en lobo, aumentando velocidad y daño.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 20,
            cooldown: 5,
            levelRequired: 8,
            effects: [
                { type: EffectType.BUFF, value: 30, scaling: 0, duration: 4 }, // +30% daño
            ],
        },
        {
            id: 'rejuvenation',
            name: 'Rejuvenation',
            displayName: 'Rejuvenecimiento',
            description: 'Cura gradual durante 6 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 25,
            cooldown: 2,
            levelRequired: 6,
            effects: [
                { type: EffectType.HOT, value: 15, scaling: 0.4, duration: 6 },
            ],
        },
        {
            id: 'entangling_roots',
            name: 'Entangling Roots',
            displayName: 'Raíces Enredadoras',
            description: 'Inmoviliza al enemigo por 2 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 30,
            cooldown: 4,
            levelRequired: 10,
            effects: [
                { type: EffectType.ROOT, value: 0, scaling: 0, duration: 2 },
                { type: EffectType.DOT, value: 10, scaling: 0.2, duration: 2, damageType: DamageType.NATURE },
            ],
        },
        {
            id: 'hurricane',
            name: 'Hurricane',
            displayName: 'Huracán',
            description: 'Tormenta de naturaleza que daña a todos los enemigos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 50,
            cooldown: 5,
            levelRequired: 18,
            effects: [
                { type: EffectType.DAMAGE, value: 50, scaling: 0.9, damageType: DamageType.NATURE },
            ],
        },
        {
            id: 'wild_growth',
            name: 'Wild Growth',
            displayName: 'Crecimiento Salvaje',
            description: 'Cura a todos los aliados durante 4 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ALLIES,
            resourceCost: 45,
            cooldown: 5,
            levelRequired: 15,
            effects: [
                { type: EffectType.HOT, value: 12, scaling: 0.3, duration: 4 },
            ],
        },
    ],
    passives: [
        {
            id: 'nature_affinity',
            name: 'Nature Affinity',
            displayName: 'Afinidad Natural',
            description: 'Regenera 2% de vida y recursos cada turno.',
            levelRequired: 5,
            effects: [{ stat: 'regenAll', value: 2, isPercentage: true }],
        },
        {
            id: 'thick_hide',
            name: 'Thick Hide',
            displayName: 'Piel Gruesa',
            description: 'Defensa aumentada en un 10%.',
            levelRequired: 10,
            effects: [{ stat: 'defense', value: 10, isPercentage: true }],
        },
        {
            id: 'heart_of_the_wild',
            name: 'Heart of the Wild',
            displayName: 'Corazón Salvaje',
            description: 'Los bonuses de las formas animales son 25% más efectivos.',
            levelRequired: 18,
            effects: [{ stat: 'shapeShiftBonus', value: 25, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.STAFF, WeaponType.MACE, WeaponType.FIST],
    allowedArmor: [ArmorType.CLOTH, ArmorType.LEATHER],
};

// ============================================
// MONK (Monje)
// ============================================

export const MONK: CharacterClass = {
    id: 'monk',
    name: 'Monk',
    displayName: 'Monje',
    description: 'Artista marcial que canaliza Ki para ataques devastadores y defensa.',
    roles: [ClassRole.DPS_MELEE, ClassRole.TANK],
    primaryStat: PrimaryStat.DEXTERITY,
    secondaryStat: PrimaryStat.VITALITY,
    resourceType: ResourceType.KI,
    resourceName: 'Ki',
    baseStats: {
        health: 100,
        resource: 100,
        strength: 12,
        dexterity: 25,
        vitality: 18,
        intelligence: 10,
        faith: 12,
        wisdom: 15,
    },
    skills: [
        {
            id: 'palm_strike',
            name: 'Palm Strike',
            displayName: 'Golpe de Palma',
            description: 'Golpe rápido que genera Ki.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 25, scaling: 1.1, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'flying_kick',
            name: 'Flying Kick',
            displayName: 'Patada Voladora',
            description: 'Patada a distancia que causa buen daño.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 20,
            cooldown: 2,
            levelRequired: 5,
            effects: [
                { type: EffectType.DAMAGE, value: 45, scaling: 1.3, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'spinning_kick',
            name: 'Spinning Kick',
            displayName: 'Patada Giratoria',
            description: 'Patada que golpea a todos los enemigos cercanos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 35,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 0.9, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'meditation',
            name: 'Meditation',
            displayName: 'Meditación',
            description: 'Recupera Ki y cura parte de tu vida.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: -40,
            cooldown: 4,
            levelRequired: 8,
            effects: [
                { type: EffectType.HEAL, value: 30, scaling: 0.4 },
            ],
        },
        {
            id: 'iron_skin',
            name: 'Iron Skin',
            displayName: 'Piel de Hierro',
            description: 'Reduce el daño recibido en un 50% por 2 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 30,
            cooldown: 5,
            levelRequired: 12,
            effects: [
                { type: EffectType.BUFF, value: 50, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'dragon_punch',
            name: 'Dragon Punch',
            displayName: 'Puño del Dragón',
            description: 'Golpe devastador cargado con Ki.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 50,
            cooldown: 4,
            levelRequired: 18,
            effects: [
                { type: EffectType.DAMAGE, value: 90, scaling: 1.8, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'counter_stance',
            name: 'Counter Stance',
            displayName: 'Postura de Contraataque',
            description: 'El próximo ataque recibido se devuelve al atacante.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 25,
            cooldown: 4,
            levelRequired: 15,
            effects: [
                { type: EffectType.BUFF, value: 100, scaling: 0, duration: 1 },
            ],
        },
    ],
    passives: [
        {
            id: 'inner_strength',
            name: 'Inner Strength',
            displayName: 'Fuerza Interior',
            description: 'Daño sin arma aumentado en un 50%.',
            levelRequired: 5,
            effects: [{ stat: 'unarmedDamage', value: 50, isPercentage: true }],
        },
        {
            id: 'agile_defense',
            name: 'Agile Defense',
            displayName: 'Defensa Ágil',
            description: '10% de probabilidad de esquivar ataques.',
            levelRequired: 10,
            effects: [{ stat: 'dodgeChance', value: 10, isPercentage: false }],
        },
        {
            id: 'one_with_self',
            name: 'One With Self',
            displayName: 'Uno con el Ser',
            description: 'Regenera 5% de vida y Ki cada turno en combate.',
            levelRequired: 18,
            effects: [{ stat: 'combatRegen', value: 5, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.FIST, WeaponType.STAFF],
    allowedArmor: [ArmorType.CLOTH, ArmorType.LEATHER],
};
