/**
 * Clases de Inteligencia: Mage, Warlock, Necromancer
 */

import {
    CharacterClass,
    ClassRole,
    ResourceType,
    PrimaryStat,
    WeaponType,
    ArmorType,
    SkillType,
    TargetType,
    EffectType,
    DamageType,
} from './types';

// ============================================
// MAGE (Mago)
// ============================================

export const MAGE: CharacterClass = {
    id: 'mage',
    name: 'Mage',
    displayName: 'Mago',
    description: 'Maestro de las artes arcanas. Domina los elementos para destruir a sus enemigos.',
    roles: [ClassRole.DPS_MAGIC],
    primaryStat: PrimaryStat.INTELLIGENCE,
    resourceType: ResourceType.MANA,
    resourceName: 'Maná',
    baseStats: {
        health: 70,
        resource: 150,
        strength: 5,
        dexterity: 8,
        vitality: 8,
        intelligence: 35,
        faith: 5,
        wisdom: 15,
    },
    skills: [
        {
            id: 'fireball',
            name: 'Fireball',
            displayName: 'Bola de Fuego',
            description: 'Lanza una bola de fuego que explota al impactar.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 20,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 40, scaling: 1.2, damageType: DamageType.FIRE },
            ],
        },
        {
            id: 'frost_bolt',
            name: 'Frost Bolt',
            displayName: 'Rayo de Escarcha',
            description: 'Disparo de hielo que daña y ralentiza al enemigo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 18,
            cooldown: 0,
            levelRequired: 3,
            effects: [
                { type: EffectType.DAMAGE, value: 30, scaling: 1.0, damageType: DamageType.ICE },
                { type: EffectType.SLOW, value: 30, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'arcane_missiles',
            name: 'Arcane Missiles',
            displayName: 'Misiles Arcanos',
            description: 'Lanza una ráfaga de proyectiles mágicos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 25,
            cooldown: 1,
            levelRequired: 6,
            effects: [
                { type: EffectType.DAMAGE, value: 50, scaling: 1.3, damageType: DamageType.LIGHTNING },
            ],
        },
        {
            id: 'blizzard',
            name: 'Blizzard',
            displayName: 'Ventisca',
            description: 'Invoca una tormenta de hielo que daña a todos los enemigos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 50,
            cooldown: 4,
            levelRequired: 15,
            effects: [
                { type: EffectType.DAMAGE, value: 45, scaling: 0.9, damageType: DamageType.ICE },
                { type: EffectType.SLOW, value: 20, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'meteor',
            name: 'Meteor',
            displayName: 'Meteoro',
            description: 'Invoca un meteoro que causa daño masivo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.AOE_ENEMIES,
            resourceCost: 80,
            cooldown: 6,
            levelRequired: 20,
            effects: [
                { type: EffectType.DAMAGE, value: 120, scaling: 1.8, damageType: DamageType.FIRE },
            ],
        },
        {
            id: 'mana_shield',
            name: 'Mana Shield',
            displayName: 'Escudo de Maná',
            description: 'Absorbe daño usando maná en lugar de vida.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 30,
            cooldown: 5,
            levelRequired: 10,
            effects: [
                { type: EffectType.SHIELD, value: 50, scaling: 0.5, duration: 3 },
            ],
        },
    ],
    passives: [
        {
            id: 'arcane_intellect',
            name: 'Arcane Intellect',
            displayName: 'Intelecto Arcano',
            description: 'Aumenta la inteligencia en un 10%.',
            levelRequired: 5,
            effects: [{ stat: 'intelligence', value: 10, isPercentage: true }],
        },
        {
            id: 'mana_regeneration',
            name: 'Mana Regeneration',
            displayName: 'Regeneración de Maná',
            description: 'Regenera un 5% de maná cada turno.',
            levelRequired: 10,
            effects: [{ stat: 'manaRegen', value: 5, isPercentage: true }],
        },
        {
            id: 'spell_power',
            name: 'Spell Power',
            displayName: 'Poder Mágico',
            description: 'Todo el daño mágico aumenta en un 15%.',
            levelRequired: 18,
            effects: [{ stat: 'spellDamage', value: 15, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.STAFF, WeaponType.WAND],
    allowedArmor: [ArmorType.CLOTH],
};

// ============================================
// WARLOCK (Brujo)
// ============================================

export const WARLOCK: CharacterClass = {
    id: 'warlock',
    name: 'Warlock',
    displayName: 'Brujo',
    description: 'Practicante de magia oscura. Usa maldiciones y demonios para destruir enemigos.',
    roles: [ClassRole.DPS_MAGIC, ClassRole.SUPPORT],
    primaryStat: PrimaryStat.INTELLIGENCE,
    resourceType: ResourceType.SOULS,
    resourceName: 'Almas',
    baseStats: {
        health: 75,
        resource: 5,  // Max souls
        strength: 5,
        dexterity: 8,
        vitality: 10,
        intelligence: 32,
        faith: 3,
        wisdom: 12,
    },
    skills: [
        {
            id: 'shadow_bolt',
            name: 'Shadow Bolt',
            displayName: 'Descarga de Sombra',
            description: 'Disparo de energía oscura.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 0,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 1.1, damageType: DamageType.SHADOW },
            ],
        },
        {
            id: 'corruption',
            name: 'Corruption',
            displayName: 'Corrupción',
            description: 'Maldice al enemigo, causando daño durante 5 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 0,
            cooldown: 2,
            levelRequired: 3,
            effects: [
                { type: EffectType.DOT, value: 20, scaling: 0.4, duration: 5, damageType: DamageType.SHADOW },
            ],
        },
        {
            id: 'drain_life',
            name: 'Drain Life',
            displayName: 'Drenar Vida',
            description: 'Roba vida del enemigo para curarte.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 0,
            cooldown: 2,
            levelRequired: 6,
            effects: [
                { type: EffectType.DAMAGE, value: 25, scaling: 0.8, damageType: DamageType.SHADOW },
                { type: EffectType.HEAL, value: 25, scaling: 0.5 },
            ],
        },
        {
            id: 'curse_of_weakness',
            name: 'Curse of Weakness',
            displayName: 'Maldición de Debilidad',
            description: 'Reduce el daño del enemigo en un 30%.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 1,
            cooldown: 4,
            levelRequired: 10,
            effects: [
                { type: EffectType.DEBUFF, value: 30, scaling: 0, duration: 4 },
            ],
        },
        {
            id: 'summon_demon',
            name: 'Summon Demon',
            displayName: 'Invocar Demonio',
            description: 'Invoca un demonio que lucha a tu lado.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 3,
            cooldown: 8,
            levelRequired: 15,
            effects: [
                { type: EffectType.SUMMON, value: 1, scaling: 0, duration: 6 },
            ],
        },
        {
            id: 'hellfire',
            name: 'Hellfire',
            displayName: 'Fuego Infernal',
            description: 'Desata llamas infernales que dañan a todos, incluyéndote.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 2,
            cooldown: 4,
            levelRequired: 18,
            effects: [
                { type: EffectType.DAMAGE, value: 70, scaling: 1.2, damageType: DamageType.FIRE },
            ],
        },
    ],
    passives: [
        {
            id: 'soul_harvest',
            name: 'Soul Harvest',
            displayName: 'Cosecha de Almas',
            description: 'Ganas 1 Alma al matar un enemigo.',
            levelRequired: 5,
            effects: [{ stat: 'soulOnKill', value: 1, isPercentage: false }],
        },
        {
            id: 'dark_pact',
            name: 'Dark Pact',
            displayName: 'Pacto Oscuro',
            description: 'Puedes sacrificar 20% de vida para ganar 2 Almas.',
            levelRequired: 12,
            effects: [{ stat: 'lifeSacrifice', value: 20, isPercentage: true }],
        },
        {
            id: 'demonic_empowerment',
            name: 'Demonic Empowerment',
            displayName: 'Empoderamiento Demoníaco',
            description: 'Tus demonios causan un 30% más de daño.',
            levelRequired: 18,
            effects: [{ stat: 'summonDamage', value: 30, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.STAFF, WeaponType.WAND, WeaponType.DAGGER],
    allowedArmor: [ArmorType.CLOTH],
};

// ============================================
// NECROMANCER (Nigromante)
// ============================================

export const NECROMANCER: CharacterClass = {
    id: 'necromancer',
    name: 'Necromancer',
    displayName: 'Nigromante',
    description: 'Maestro de la muerte. Controla ejércitos de no-muertos.',
    roles: [ClassRole.DPS_MAGIC, ClassRole.SUPPORT],
    primaryStat: PrimaryStat.INTELLIGENCE,
    resourceType: ResourceType.ESSENCE,
    resourceName: 'Esencia',
    baseStats: {
        health: 72,
        resource: 100,
        strength: 5,
        dexterity: 6,
        vitality: 12,
        intelligence: 30,
        faith: 3,
        wisdom: 15,
    },
    skills: [
        {
            id: 'bone_spear',
            name: 'Bone Spear',
            displayName: 'Lanza de Hueso',
            description: 'Lanza un proyectil de hueso.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 1.1, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'summon_skeleton',
            name: 'Summon Skeleton',
            displayName: 'Invocar Esqueleto',
            description: 'Invoca un guerrero esqueleto.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 25,
            cooldown: 3,
            levelRequired: 3,
            effects: [
                { type: EffectType.SUMMON, value: 1, scaling: 0, duration: 8 },
            ],
        },
        {
            id: 'corpse_explosion',
            name: 'Corpse Explosion',
            displayName: 'Explosión Cadavérica',
            description: 'Hace explotar los cadáveres causando daño masivo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.AOE_ENEMIES,
            resourceCost: 40,
            cooldown: 4,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 80, scaling: 1.0, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'curse_of_frailty',
            name: 'Curse of Frailty',
            displayName: 'Maldición de Fragilidad',
            description: 'El enemigo recibe un 25% más de daño.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 20,
            cooldown: 5,
            levelRequired: 8,
            effects: [
                { type: EffectType.DEBUFF, value: 25, scaling: 0, duration: 4 },
            ],
        },
        {
            id: 'army_of_the_dead',
            name: 'Army of the Dead',
            displayName: 'Ejército de Muertos',
            description: 'Invoca múltiples esqueletos para devastar al enemigo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 70,
            cooldown: 10,
            levelRequired: 20,
            effects: [
                { type: EffectType.SUMMON, value: 5, scaling: 0, duration: 4 },
            ],
        },
        {
            id: 'drain_essence',
            name: 'Drain Essence',
            displayName: 'Drenar Esencia',
            description: 'Drena esencia de los enemigos para recuperar recurso.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -30,
            cooldown: 3,
            levelRequired: 6,
            effects: [
                { type: EffectType.DAMAGE, value: 25, scaling: 0.7, damageType: DamageType.SHADOW },
            ],
        },
    ],
    passives: [
        {
            id: 'death_mastery',
            name: 'Death Mastery',
            displayName: 'Maestría de la Muerte',
            description: 'Los minions tienen un 20% más de vida.',
            levelRequired: 5,
            effects: [{ stat: 'minionHealth', value: 20, isPercentage: true }],
        },
        {
            id: 'bone_armor',
            name: 'Bone Armor',
            displayName: 'Armadura de Hueso',
            description: 'Defensa aumentada en un 15%.',
            levelRequired: 12,
            effects: [{ stat: 'defense', value: 15, isPercentage: true }],
        },
        {
            id: 'eternal_servitude',
            name: 'Eternal Servitude',
            displayName: 'Servidumbre Eterna',
            description: 'Puedes tener 2 minions adicionales activos.',
            levelRequired: 18,
            effects: [{ stat: 'maxMinions', value: 2, isPercentage: false }],
        },
    ],
    allowedWeapons: [WeaponType.STAFF, WeaponType.WAND, WeaponType.DAGGER],
    allowedArmor: [ArmorType.CLOTH],
};
