/**
 * Clases de Fuerza: Warrior, Paladin, Berserker
 */

import {
    CharacterClass,
    ClassRole,
    ResourceType,
    PrimaryStat,
    WeaponType,
    ArmorType,
    SkillType,
    TargetType,
    EffectType,
    DamageType,
} from './types';

// ============================================
// WARRIOR (Guerrero)
// ============================================

export const WARRIOR: CharacterClass = {
    id: 'warrior',
    name: 'Warrior',
    displayName: 'Guerrero',
    description: 'Un combatiente versátil experto en armas y defensa. Puede actuar como tanque o DPS.',
    roles: [ClassRole.TANK, ClassRole.DPS_MELEE],
    primaryStat: PrimaryStat.STRENGTH,
    secondaryStat: PrimaryStat.VITALITY,
    resourceType: ResourceType.FURY,
    resourceName: 'Furia',
    baseStats: {
        health: 120,
        resource: 100,
        strength: 25,
        dexterity: 10,
        vitality: 20,
        intelligence: 5,
        faith: 5,
        wisdom: 5,
    },
    skills: [
        {
            id: 'heroic_strike',
            name: 'Heroic Strike',
            displayName: 'Golpe Heroico',
            description: 'Un poderoso golpe que inflige daño y genera Furia.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -15, // Genera recurso
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 25, scaling: 1.2, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'shield_wall',
            name: 'Shield Wall',
            displayName: 'Muro de Escudos',
            description: 'Reduce el daño recibido en un 40% durante 3 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 30,
            cooldown: 5,
            levelRequired: 5,
            effects: [
                { type: EffectType.BUFF, value: 40, scaling: 0, duration: 3 },
            ],
        },
        {
            id: 'war_cry',
            name: 'War Cry',
            displayName: 'Grito de Guerra',
            description: 'Aumenta el daño de todos los aliados en un 20% durante 3 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ALLIES,
            resourceCost: 25,
            cooldown: 4,
            levelRequired: 8,
            effects: [
                { type: EffectType.BUFF, value: 20, scaling: 0, duration: 3 },
            ],
        },
        {
            id: 'charge',
            name: 'Charge',
            displayName: 'Carga',
            description: 'Carga hacia el enemigo causando daño y aturdiendo por 1 turno.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 20,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 1.0, damageType: DamageType.PHYSICAL },
                { type: EffectType.STUN, value: 0, scaling: 0, duration: 1 },
            ],
        },
        {
            id: 'whirlwind',
            name: 'Whirlwind',
            displayName: 'Torbellino',
            description: 'Gira causando daño a todos los enemigos cercanos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 40,
            cooldown: 4,
            levelRequired: 15,
            effects: [
                { type: EffectType.DAMAGE, value: 30, scaling: 0.8, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'execute',
            name: 'Execute',
            displayName: 'Ejecución',
            description: 'Golpe devastador que causa 50% más daño a enemigos con menos del 20% de vida.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 35,
            cooldown: 2,
            levelRequired: 20,
            effects: [
                { type: EffectType.DAMAGE, value: 60, scaling: 1.5, damageType: DamageType.PHYSICAL },
            ],
        },
    ],
    passives: [
        {
            id: 'iron_skin',
            name: 'Iron Skin',
            displayName: 'Piel de Hierro',
            description: 'Aumenta la defensa en un 15%.',
            levelRequired: 5,
            effects: [{ stat: 'defense', value: 15, isPercentage: true }],
        },
        {
            id: 'weapon_mastery',
            name: 'Weapon Mastery',
            displayName: 'Maestría de Armas',
            description: 'Aumenta el daño físico en un 10%.',
            levelRequired: 10,
            effects: [{ stat: 'physicalDamage', value: 10, isPercentage: true }],
        },
        {
            id: 'last_stand',
            name: 'Last Stand',
            displayName: 'Última Resistencia',
            description: 'Cuando la vida baja del 30%, reduce el daño recibido en un 20%.',
            levelRequired: 20,
            effects: [{ stat: 'damageReduction', value: 20, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.SWORD, WeaponType.AXE, WeaponType.MACE, WeaponType.POLEARM, WeaponType.SHIELD],
    allowedArmor: [ArmorType.MAIL, ArmorType.PLATE],
};

// ============================================
// PALADIN (Paladín)
// ============================================

export const PALADIN: CharacterClass = {
    id: 'paladin',
    name: 'Paladin',
    displayName: 'Paladín',
    description: 'Guerrero sagrado que combina fuerza marcial con poderes divinos de curación y protección.',
    roles: [ClassRole.TANK, ClassRole.HEALER],
    primaryStat: PrimaryStat.STRENGTH,
    secondaryStat: PrimaryStat.FAITH,
    resourceType: ResourceType.HOLY_MANA,
    resourceName: 'Maná Sagrado',
    baseStats: {
        health: 110,
        resource: 100,
        strength: 20,
        dexterity: 8,
        vitality: 18,
        intelligence: 10,
        faith: 18,
        wisdom: 10,
    },
    skills: [
        {
            id: 'holy_strike',
            name: 'Holy Strike',
            displayName: 'Golpe Sagrado',
            description: 'Golpe imbuido de luz sagrada que daña y cura al usuario.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 15,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 20, scaling: 1.0, damageType: DamageType.HOLY },
                { type: EffectType.HEAL, value: 10, scaling: 0.3 },
            ],
        },
        {
            id: 'lay_on_hands',
            name: 'Lay on Hands',
            displayName: 'Imposición de Manos',
            description: 'Curación masiva que restaura toda la vida del objetivo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 100,
            cooldown: 10,
            levelRequired: 15,
            effects: [
                { type: EffectType.HEAL, value: 999, scaling: 0 },
            ],
        },
        {
            id: 'devotion_aura',
            name: 'Devotion Aura',
            displayName: 'Aura de Devoción',
            description: 'Aumenta la resistencia de todos los aliados durante 5 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ALLIES,
            resourceCost: 40,
            cooldown: 6,
            levelRequired: 10,
            effects: [
                { type: EffectType.BUFF, value: 25, scaling: 0, duration: 5 },
            ],
        },
        {
            id: 'divine_shield',
            name: 'Divine Shield',
            displayName: 'Escudo Divino',
            description: 'Inmunidad total durante 2 turnos, pero no puede atacar.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 50,
            cooldown: 8,
            levelRequired: 20,
            effects: [
                { type: EffectType.SHIELD, value: 999, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'judgement',
            name: 'Judgement',
            displayName: 'Juicio',
            description: 'Castiga al enemigo con daño sagrado.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 25,
            cooldown: 2,
            levelRequired: 5,
            effects: [
                { type: EffectType.DAMAGE, value: 40, scaling: 0.8, damageType: DamageType.HOLY },
            ],
        },
        {
            id: 'flash_of_light',
            name: 'Flash of Light',
            displayName: 'Destello de Luz',
            description: 'Curación rápida de un aliado.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ALLY,
            resourceCost: 20,
            cooldown: 0,
            levelRequired: 8,
            effects: [
                { type: EffectType.HEAL, value: 35, scaling: 0.6 },
            ],
        },
    ],
    passives: [
        {
            id: 'divine_protection',
            name: 'Divine Protection',
            displayName: 'Protección Divina',
            description: 'Aumenta la vida máxima en un 10%.',
            levelRequired: 5,
            effects: [{ stat: 'maxHealth', value: 10, isPercentage: true }],
        },
        {
            id: 'holy_light',
            name: 'Holy Light',
            displayName: 'Luz Sagrada',
            description: 'Las curaciones son un 15% más efectivas.',
            levelRequired: 12,
            effects: [{ stat: 'healingPower', value: 15, isPercentage: true }],
        },
        {
            id: 'shield_of_faith',
            name: 'Shield of Faith',
            displayName: 'Escudo de Fe',
            description: 'Probabilidad de bloqueo aumentada en un 10%.',
            levelRequired: 18,
            effects: [{ stat: 'blockChance', value: 10, isPercentage: false }],
        },
    ],
    allowedWeapons: [WeaponType.SWORD, WeaponType.MACE, WeaponType.SHIELD],
    allowedArmor: [ArmorType.MAIL, ArmorType.PLATE],
};

// ============================================
// BERSERKER (Berserker)
// ============================================

export const BERSERKER: CharacterClass = {
    id: 'berserker',
    name: 'Berserker',
    displayName: 'Berserker',
    description: 'Guerrero salvaje que canaliza su ira para causar daño devastador. Más peligroso cuando está herido.',
    roles: [ClassRole.DPS_MELEE],
    primaryStat: PrimaryStat.STRENGTH,
    resourceType: ResourceType.RAGE,
    resourceName: 'Ira',
    baseStats: {
        health: 100,
        resource: 100,
        strength: 30,
        dexterity: 12,
        vitality: 15,
        intelligence: 3,
        faith: 3,
        wisdom: 3,
    },
    skills: [
        {
            id: 'bloody_strike',
            name: 'Bloody Strike',
            displayName: 'Golpe Sangriento',
            description: 'Ataque básico que genera Ira.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: -20,
            cooldown: 0,
            levelRequired: 1,
            effects: [
                { type: EffectType.DAMAGE, value: 30, scaling: 1.3, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'bloodthirst',
            name: 'Bloodthirst',
            displayName: 'Sed de Sangre',
            description: 'Ataque que roba vida del enemigo.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 30,
            cooldown: 2,
            levelRequired: 5,
            effects: [
                { type: EffectType.DAMAGE, value: 35, scaling: 1.1, damageType: DamageType.PHYSICAL },
                { type: EffectType.HEAL, value: 20, scaling: 0.4 },
            ],
        },
        {
            id: 'rampage',
            name: 'Rampage',
            displayName: 'Frenesí',
            description: 'Serie de ataques salvajes. Más daño con menos vida.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 50,
            cooldown: 4,
            levelRequired: 12,
            effects: [
                { type: EffectType.DAMAGE, value: 80, scaling: 1.8, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'whirlwind_rage',
            name: 'Whirlwind Rage',
            displayName: 'Torbellino de Ira',
            description: 'Ataque giratorio que daña a todos los enemigos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.ALL_ENEMIES,
            resourceCost: 40,
            cooldown: 3,
            levelRequired: 10,
            effects: [
                { type: EffectType.DAMAGE, value: 40, scaling: 1.0, damageType: DamageType.PHYSICAL },
            ],
        },
        {
            id: 'reckless_charge',
            name: 'Reckless Charge',
            displayName: 'Carga Temeraria',
            description: 'Carga que causa gran daño pero reduce tu defensa.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SINGLE_ENEMY,
            resourceCost: 25,
            cooldown: 2,
            levelRequired: 8,
            effects: [
                { type: EffectType.DAMAGE, value: 50, scaling: 1.4, damageType: DamageType.PHYSICAL },
                { type: EffectType.DEBUFF, value: 20, scaling: 0, duration: 2 },
            ],
        },
        {
            id: 'enrage',
            name: 'Enrage',
            displayName: 'Enfurecer',
            description: 'Aumenta tu daño en un 50% durante 4 turnos.',
            type: SkillType.ACTIVE,
            targetType: TargetType.SELF,
            resourceCost: 35,
            cooldown: 6,
            levelRequired: 15,
            effects: [
                { type: EffectType.BUFF, value: 50, scaling: 0, duration: 4 },
            ],
        },
    ],
    passives: [
        {
            id: 'bloodlust',
            name: 'Bloodlust',
            displayName: 'Sed de Sangre',
            description: 'Daño aumenta un 2% por cada 10% de vida perdida.',
            levelRequired: 5,
            effects: [{ stat: 'lowHealthDamage', value: 2, isPercentage: true }],
        },
        {
            id: 'fury_generation',
            name: 'Fury Generation',
            displayName: 'Generación de Furia',
            description: 'Genera un 20% más de Ira.',
            levelRequired: 10,
            effects: [{ stat: 'resourceGeneration', value: 20, isPercentage: true }],
        },
        {
            id: 'death_wish',
            name: 'Death Wish',
            displayName: 'Deseo de Muerte',
            description: 'Cuando la vida baja del 20%, el daño aumenta un 50%.',
            levelRequired: 20,
            effects: [{ stat: 'criticalHealthDamage', value: 50, isPercentage: true }],
        },
    ],
    allowedWeapons: [WeaponType.AXE, WeaponType.SWORD, WeaponType.MACE],
    allowedArmor: [ArmorType.LEATHER, ArmorType.MAIL],
};
